### ISSUE TITLE
ODC website down

### ISSUE THREAD

**Issue by pnorman** [okfn/opendatacommons#1]
Cloudflare reports an Error 522 when trying to connect to opendatacommons.org

I can't find any other reporting channels.

**Comment by Stephen-Gates** [comment]
Was also reported in 
- https://discuss.okfn.org/t/http-opendatacommons-org-down/6564
- https://discuss.okfn.org/t/open-data-commons-licences/6553

**Comment by rufuspollock** [comment]
@pnorman we're investigating this and it should be up asap.

**Comment by rufuspollock** [comment]
FIXED. Details of fix on https://discuss.okfn.org/t/http-opendatacommons-org-down/6564/3
